### Register
POST http://localhost:4000/auth/register HTTP/1.1
content-type: application/json

{
    "name": "Sherifdeen Adebayo",
    "email": "herdeybayor4real+4@gmail.com",
    "password": "password",
    "level": "300",
    "departmentId": "641057990e5e6e04a904facb",
    "matric": "210551003"
}

### Login
POST http://localhost:4000/auth/login HTTP/1.1
Content-Type: application/json

{
    "matric": "210551003",
    "password": "password"
}

### Get all users
GET http://localhost:4000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MTA0YzU4YzJiOTYzZmU3ZjdkYzJmNyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3ODc5NDU2MywiZXhwIjoxNjc4Nzk4MTYzfQ.M9OqAj3vExxt5rzRP1L6so5AQzXKhySqmvHnTOthm34